/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/admin/banners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Banners */
    get: operations['list_banners_api_v1_admin_banners_get'];
    put?: never;
    /** Create Banner */
    post: operations['create_banner_api_v1_admin_banners_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/banners/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder Banners */
    post: operations['reorder_banners_api_v1_admin_banners_reorder_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/banners/{banner_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Banner */
    delete: operations['delete_banner_api_v1_admin_banners__banner_id__delete'];
    options?: never;
    head?: never;
    /** Update Banner */
    patch: operations['update_banner_api_v1_admin_banners__banner_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations['list_categories_api_v1_admin_categories_get'];
    put?: never;
    /** Create Category */
    post: operations['create_category_api_v1_admin_categories_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/categories/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder Categories */
    post: operations['reorder_categories_api_v1_admin_categories_reorder_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/categories/{category_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Category */
    delete: operations['delete_category_api_v1_admin_categories__category_id__delete'];
    options?: never;
    head?: never;
    /** Update Category */
    patch: operations['update_category_api_v1_admin_categories__category_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Products */
    get: operations['list_products_api_v1_admin_products_get'];
    put?: never;
    /** Create Product */
    post: operations['create_product_api_v1_admin_products_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations['get_product_api_v1_admin_products__product_id__get'];
    put?: never;
    post?: never;
    /**
     * Archive Product
     * @description Archives rather than deletes: past orders keep pointing at the product.
     */
    delete: operations['archive_product_api_v1_admin_products__product_id__delete'];
    options?: never;
    head?: never;
    /** Update Product */
    patch: operations['update_product_api_v1_admin_products__product_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore Product */
    post: operations['restore_product_api_v1_admin_products__product_id__restore_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/stock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set Stock */
    patch: operations['set_stock_api_v1_admin_products__product_id__stock_patch'];
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/stock-adjust': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Adjust Stock */
    post: operations['adjust_stock_api_v1_admin_products__product_id__stock_adjust_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/uploads/images': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Image */
    post: operations['upload_image_api_v1_admin_uploads_images_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/dev-login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dev Login */
    post: operations['dev_login_api_v1_auth_dev_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/google': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign In With Google */
    post: operations['sign_in_with_google_api_v1_auth_google_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Cart */
    get: operations['get_cart_api_v1_cart_get'];
    put?: never;
    post?: never;
    /** Clear Cart */
    delete: operations['clear_cart_api_v1_cart_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart/items/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set Item Quantity
     * @description Sets an absolute quantity (0 removes). Safe to retry: the same call gives the same cart.
     */
    put: operations['set_item_quantity_api_v1_cart_items__product_id__put'];
    post?: never;
    /** Remove Item */
    delete: operations['remove_item_api_v1_cart_items__product_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations['list_categories_api_v1_categories_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Category */
    get: operations['get_category_api_v1_categories__slug__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/favourites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Favourites */
    get: operations['list_favourites_api_v1_favourites_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/favourites/ids': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Favourite Ids
     * @description Lightweight: lets the app draw filled hearts without fetching full products.
     */
    get: operations['favourite_ids_api_v1_favourites_ids_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/favourites/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Add Favourite */
    put: operations['add_favourite_api_v1_favourites__product_id__put'];
    post?: never;
    /** Remove Favourite */
    delete: operations['remove_favourite_api_v1_favourites__product_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness: the process is up.
     */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/db': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Db
     * @description Readiness: the database answers.
     */
    get: operations['health_db_api_v1_health_db_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/home': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Home
     * @description Everything the home screen needs in one round trip.
     */
    get: operations['get_home_api_v1_home_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations['get_me_api_v1_me_get'];
    put?: never;
    post?: never;
    /** Delete Me */
    delete: operations['delete_me_api_v1_me_delete'];
    options?: never;
    head?: never;
    /** Update Me */
    patch: operations['update_me_api_v1_me_patch'];
    trace?: never;
  };
  '/api/v1/me/devices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register Device */
    post: operations['register_device_api_v1_me_devices_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/devices/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Device */
    delete: operations['remove_device_api_v1_me_devices__token__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Products */
    get: operations['list_products_api_v1_products_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/suggest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Suggest Products */
    get: operations['suggest_products_api_v1_products_suggest_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations['get_product_api_v1_products__product_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/shop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Shop */
    get: operations['get_shop_api_v1_shop_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminBannerOut */
    AdminBannerOut: {
      /** Ends At */
      ends_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Key */
      image_key: string | null;
      /** Image Url */
      image_url: string | null;
      /** Is Active */
      is_active: boolean;
      /** Is Live */
      is_live: boolean;
      /** Sort Order */
      sort_order: number;
      /** Starts At */
      starts_at: string | null;
      /** Subtitle */
      subtitle: string | null;
      /** Target Id */
      target_id: string | null;
      /** Target Label */
      target_label: string | null;
      /**
       * Target Type
       * @enum {string}
       */
      target_type: 'NONE' | 'CATEGORY' | 'PRODUCT';
      /** Title */
      title: string;
    };
    /** AdminCategoryOut */
    AdminCategoryOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Key */
      image_key: string | null;
      /** Image Url */
      image_url: string | null;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name: string;
      /** Product Count */
      product_count: number;
      /** Slug */
      slug: string;
      /** Sort Order */
      sort_order: number;
    };
    /** AdminProductOut */
    AdminProductOut: {
      /** Archived At */
      archived_at: string | null;
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Category Name */
      category_name: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Key */
      image_key: string | null;
      /** Image Url */
      image_url: string | null;
      /** Is Active */
      is_active: boolean;
      /** Is Featured */
      is_featured: boolean;
      /** Is Low Stock */
      is_low_stock: boolean;
      /** Low Stock Threshold */
      low_stock_threshold: number | null;
      /** Max Per Order */
      max_per_order: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /** Search Keywords */
      search_keywords: string | null;
      /** Slug */
      slug: string;
      /** Stock Quantity */
      stock_quantity: number;
      /** Unit Label */
      unit_label: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** AuthResponse */
    AuthResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /** Is New User */
      is_new_user: boolean;
      /** Refresh Token */
      refresh_token?: string | null;
      /**
       * Token Type
       * @default bearer
       * @constant
       */
      token_type?: 'bearer';
      user: components['schemas']['UserOut'];
    };
    /** BannerCreate */
    BannerCreate: {
      /** Ends At */
      ends_at?: string | null;
      /** Image Key */
      image_key?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /** Starts At */
      starts_at?: string | null;
      /** Subtitle */
      subtitle?: string | null;
      /** Target Id */
      target_id?: string | null;
      /**
       * Target Type
       * @default NONE
       * @enum {string}
       */
      target_type?: 'NONE' | 'CATEGORY' | 'PRODUCT';
      /** Title */
      title: string;
    };
    /** BannerOut */
    BannerOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Subtitle */
      subtitle: string | null;
      /** Target Id */
      target_id: string | null;
      /** Target Slug */
      target_slug: string | null;
      /**
       * Target Type
       * @enum {string}
       */
      target_type: 'NONE' | 'CATEGORY' | 'PRODUCT';
      /** Title */
      title: string;
    };
    /** BannerUpdate */
    BannerUpdate: {
      /** Ends At */
      ends_at?: string | null;
      /** Image Key */
      image_key?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /**
       * Remove Image
       * @default false
       */
      remove_image?: boolean;
      /** Starts At */
      starts_at?: string | null;
      /** Subtitle */
      subtitle?: string | null;
      /** Target Id */
      target_id?: string | null;
      /** Target Type */
      target_type?: ('NONE' | 'CATEGORY' | 'PRODUCT') | null;
      /** Title */
      title?: string | null;
    };
    /** Body_upload_image_api_v1_admin_uploads_images_post */
    Body_upload_image_api_v1_admin_uploads_images_post: {
      /** File */
      file: string;
    };
    /** CartLineOut */
    CartLineOut: {
      /** Available Quantity */
      available_quantity: number;
      /** Issue */
      issue: ('UNAVAILABLE' | 'OUT_OF_STOCK' | 'QUANTITY_REDUCED') | null;
      /** Line Total Paise */
      line_total_paise: number;
      product: components['schemas']['ProductCardOut'];
      /** Quantity */
      quantity: number;
    };
    /** CartOut */
    CartOut: {
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Free Delivery Remaining Paise */
      free_delivery_remaining_paise: number;
      /** Has Issues */
      has_issues: boolean;
      /** Item Count */
      item_count: number;
      /** Lines */
      lines: components['schemas']['CartLineOut'][];
      /** Min Order Remaining Paise */
      min_order_remaining_paise: number;
      rules: components['schemas']['DeliveryRules'];
      /** Subtotal Paise */
      subtotal_paise: number;
      /** Total Paise */
      total_paise: number;
    };
    /** CategoryCreate */
    CategoryCreate: {
      /** Image Key */
      image_key?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /** Name */
      name: string;
    };
    /** CategoryOut */
    CategoryOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** CategoryRef */
    CategoryRef: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** CategoryUpdate */
    CategoryUpdate: {
      /** Image Key */
      image_key?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Name */
      name?: string | null;
      /**
       * Remove Image
       * @default false
       */
      remove_image?: boolean;
    };
    /**
     * DeliveryRules
     * @description Sent so the app can estimate totals instantly while a change is in flight.
     */
    DeliveryRules: {
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Free Delivery Above Paise */
      free_delivery_above_paise: number;
      /** Min Order Paise */
      min_order_paise: number;
    };
    /** DevSignInRequest */
    DevSignInRequest: {
      /** @default mobile */
      client?: components['schemas']['SessionClient'];
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Name */
      name?: string | null;
    };
    /** DeviceRegistration */
    DeviceRegistration: {
      /**
       * Platform
       * @default android
       * @constant
       */
      platform?: 'android';
      /** Token */
      token: string;
    };
    /** GoogleSignInRequest */
    GoogleSignInRequest: {
      /** @default mobile */
      client?: components['schemas']['SessionClient'];
      /** Id Token */
      id_token: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status?: 'ok';
    };
    /** HomeOut */
    HomeOut: {
      /** Banners */
      banners: components['schemas']['BannerOut'][];
      /** Categories */
      categories: components['schemas']['CategoryOut'][];
      /** Featured */
      featured: components['schemas']['ProductCardOut'][];
    };
    /** LogoutRequest */
    LogoutRequest: {
      /** Device Token */
      device_token?: string | null;
    };
    /** Page[AdminProductOut] */
    Page_AdminProductOut_: {
      /** Items */
      items: components['schemas']['AdminProductOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[ProductCardOut] */
    Page_ProductCardOut_: {
      /** Items */
      items: components['schemas']['ProductCardOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** ProductCardOut */
    ProductCardOut: {
      /** Discount Percent */
      discount_percent: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Is Available */
      is_available: boolean;
      /** Max Per Order */
      max_per_order: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /**
       * Stock Hint
       * @enum {string}
       */
      stock_hint: 'IN_STOCK' | 'LOW' | 'OUT';
      /** Unit Label */
      unit_label: string;
    };
    /** ProductCreate */
    ProductCreate: {
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Description */
      description?: string | null;
      /** Image Key */
      image_key?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /**
       * Is Featured
       * @default false
       */
      is_featured?: boolean;
      /** Low Stock Threshold */
      low_stock_threshold?: number | null;
      /** Max Per Order */
      max_per_order?: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /** Search Keywords */
      search_keywords?: string | null;
      /**
       * Stock Quantity
       * @default 0
       */
      stock_quantity?: number;
      /** Unit Label */
      unit_label: string;
    };
    /** ProductDetailOut */
    ProductDetailOut: {
      category: components['schemas']['CategoryRef'];
      /** Description */
      description: string | null;
      /** Discount Percent */
      discount_percent: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Is Available */
      is_available: boolean;
      /** Max Per Order */
      max_per_order: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /** Related */
      related: components['schemas']['ProductCardOut'][];
      /**
       * Stock Hint
       * @enum {string}
       */
      stock_hint: 'IN_STOCK' | 'LOW' | 'OUT';
      /** Unit Label */
      unit_label: string;
    };
    /**
     * ProductUpdate
     * @description Stock is not editable here: it goes through the stock endpoints so every change is logged.
     */
    ProductUpdate: {
      /** Category Id */
      category_id?: string | null;
      /** Description */
      description?: string | null;
      /** Image Key */
      image_key?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Is Featured */
      is_featured?: boolean | null;
      /** Low Stock Threshold */
      low_stock_threshold?: number | null;
      /** Max Per Order */
      max_per_order?: number | null;
      /** Mrp Paise */
      mrp_paise?: number | null;
      /** Name */
      name?: string | null;
      /** Price Paise */
      price_paise?: number | null;
      /**
       * Remove Image
       * @default false
       */
      remove_image?: boolean;
      /** Search Keywords */
      search_keywords?: string | null;
      /** Unit Label */
      unit_label?: string | null;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token?: string | null;
    };
    /** ReorderRequest */
    ReorderRequest: {
      /** Ids */
      ids: string[];
    };
    /**
     * SessionClient
     * @enum {string}
     */
    SessionClient: 'mobile' | 'admin';
    /** SetQuantityRequest */
    SetQuantityRequest: {
      /**
       * Quantity
       * @description 0 removes the item
       */
      quantity: number;
    };
    /** ShopOut */
    ShopOut: {
      /** Closed Message */
      closed_message: string;
      /** Cod Enabled */
      cod_enabled: boolean;
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Free Delivery Above Paise */
      free_delivery_above_paise: number;
      /** Is Accepting Orders */
      is_accepting_orders: boolean;
      /** Min Order Paise */
      min_order_paise: number;
      /** Name */
      name: string;
      /** Online Payment Enabled */
      online_payment_enabled: boolean;
      /** Phone */
      phone: string | null;
    };
    /** StockAdjustRequest */
    StockAdjustRequest: {
      /** Delta */
      delta: number;
      /** Note */
      note?: string | null;
    };
    /** StockOut */
    StockOut: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Stock Quantity */
      stock_quantity: number;
    };
    /** StockSetRequest */
    StockSetRequest: {
      /** Expected Stock */
      expected_stock: number;
      /** Stock */
      stock: number;
    };
    /** SuggestionOut */
    SuggestionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Name */
      name: string;
      /** Unit Label */
      unit_label: string;
    };
    /** UpdateMeRequest */
    UpdateMeRequest: {
      /** Name */
      name?: string | null;
      /** Phone */
      phone?: string | null;
    };
    /** UploadOut */
    UploadOut: {
      /** Key */
      key: string;
      /** Url */
      url: string;
    };
    /** UserOut */
    UserOut: {
      /** Avatar Url */
      avatar_url: string | null;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Needs Onboarding */
      needs_onboarding: boolean;
      /** Phone */
      phone: string | null;
      role: components['schemas']['UserRole'];
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: 'CUSTOMER' | 'ADMIN';
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_banners_api_v1_admin_banners_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminBannerOut'][];
        };
      };
    };
  };
  create_banner_api_v1_admin_banners_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BannerCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminBannerOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reorder_banners_api_v1_admin_banners_reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_banner_api_v1_admin_banners__banner_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        banner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_banner_api_v1_admin_banners__banner_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        banner_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BannerUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminBannerOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_categories_api_v1_admin_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategoryOut'][];
        };
      };
    };
  };
  create_category_api_v1_admin_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reorder_categories_api_v1_admin_categories_reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_category_api_v1_admin_categories__category_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_category_api_v1_admin_categories__category_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_products_api_v1_admin_products_get: {
    parameters: {
      query?: {
        q?: string | null;
        category_id?: string | null;
        status?: 'active' | 'inactive' | 'archived' | 'all';
        low_stock?: boolean;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AdminProductOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_product_api_v1_admin_products_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_product_api_v1_admin_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  archive_product_api_v1_admin_products__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_product_api_v1_admin_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  restore_product_api_v1_admin_products__product_id__restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_stock_api_v1_admin_products__product_id__stock_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StockSetRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StockOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  adjust_stock_api_v1_admin_products__product_id__stock_adjust_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StockAdjustRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StockOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_image_api_v1_admin_uploads_images_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_image_api_v1_admin_uploads_images_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  dev_login_api_v1_auth_dev_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DevSignInRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  sign_in_with_google_api_v1_auth_google_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleSignInRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['LogoutRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['RefreshRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_cart_api_v1_cart_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
    };
  };
  clear_cart_api_v1_cart_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
    };
  };
  set_item_quantity_api_v1_cart_items__product_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetQuantityRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_item_api_v1_cart_items__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_categories_api_v1_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOut'][];
        };
      };
    };
  };
  get_category_api_v1_categories__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_favourites_api_v1_favourites_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ProductCardOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  favourite_ids_api_v1_favourites_ids_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string[];
        };
      };
    };
  };
  add_favourite_api_v1_favourites__product_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_favourite_api_v1_favourites__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  health_db_api_v1_health_db_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  get_home_api_v1_home_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HomeOut'];
        };
      };
    };
  };
  get_me_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  delete_me_api_v1_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_me_api_v1_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_device_api_v1_me_devices_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeviceRegistration'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_device_api_v1_me_devices__token__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_products_api_v1_products_get: {
    parameters: {
      query?: {
        /** @description Search text; ranks by relevance */
        q?: string | null;
        category_id?: string | null;
        in_stock_only?: boolean;
        sort?: 'default' | 'price_asc' | 'price_desc';
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ProductCardOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  suggest_products_api_v1_products_suggest_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuggestionOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_product_api_v1_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductDetailOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_shop_api_v1_shop_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShopOut'];
        };
      };
    };
  };
}
