/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/addresses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Addresses
     * @description The default address comes first, then the newest.
     */
    get: operations['list_addresses_api_v1_addresses_get'];
    put?: never;
    /**
     * Create Address
     * @description The first address becomes the default. Unserviceable pincodes are saved but flagged.
     */
    post: operations['create_address_api_v1_addresses_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/addresses/{address_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Address
     * @description Deleting the default promotes the most recently used remaining address.
     */
    delete: operations['delete_address_api_v1_addresses__address_id__delete'];
    options?: never;
    head?: never;
    /** Update Address */
    patch: operations['update_address_api_v1_addresses__address_id__patch'];
    trace?: never;
  };
  '/api/v1/addresses/{address_id}/default': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Set Default Address */
    post: operations['set_default_address_api_v1_addresses__address_id__default_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/banners': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Banners */
    get: operations['list_banners_api_v1_admin_banners_get'];
    put?: never;
    /** Create Banner */
    post: operations['create_banner_api_v1_admin_banners_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/banners/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder Banners */
    post: operations['reorder_banners_api_v1_admin_banners_reorder_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/banners/{banner_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Banner */
    delete: operations['delete_banner_api_v1_admin_banners__banner_id__delete'];
    options?: never;
    head?: never;
    /** Update Banner */
    patch: operations['update_banner_api_v1_admin_banners__banner_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations['list_categories_api_v1_admin_categories_get'];
    put?: never;
    /** Create Category */
    post: operations['create_category_api_v1_admin_categories_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/categories/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Reorder Categories */
    post: operations['reorder_categories_api_v1_admin_categories_reorder_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/categories/{category_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Category */
    delete: operations['delete_category_api_v1_admin_categories__category_id__delete'];
    options?: never;
    head?: never;
    /** Update Category */
    patch: operations['update_category_api_v1_admin_categories__category_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/dashboard': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Dashboard */
    get: operations['dashboard_api_v1_admin_dashboard_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Orders
     * @description Newest first. Without `status`, unpaid online orders (AWAITING_PAYMENT) are hidden.
     *     `q` matches the order number, customer name or phone. Dates are in the shop's timezone.
     */
    get: operations['list_orders_api_v1_admin_orders_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/orders/summary': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Orders Summary */
    get: operations['orders_summary_api_v1_admin_orders_summary_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/orders/{order_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Order */
    get: operations['get_order_api_v1_admin_orders__order_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/orders/{order_id}/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Change Status
     * @description Moves the order one step. Cancelling needs a `note` (shown to the customer) and puts
     *     the stock back.
     */
    patch: operations['change_status_api_v1_admin_orders__order_id__status_patch'];
    trace?: never;
  };
  '/api/v1/admin/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Products */
    get: operations['list_products_api_v1_admin_products_get'];
    put?: never;
    /** Create Product */
    post: operations['create_product_api_v1_admin_products_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations['get_product_api_v1_admin_products__product_id__get'];
    put?: never;
    post?: never;
    /**
     * Archive Product
     * @description Archives rather than deletes: past orders keep pointing at the product.
     */
    delete: operations['archive_product_api_v1_admin_products__product_id__delete'];
    options?: never;
    head?: never;
    /** Update Product */
    patch: operations['update_product_api_v1_admin_products__product_id__patch'];
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/restore': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Restore Product */
    post: operations['restore_product_api_v1_admin_products__product_id__restore_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/stock': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Set Stock */
    patch: operations['set_stock_api_v1_admin_products__product_id__stock_patch'];
    trace?: never;
  };
  '/api/v1/admin/products/{product_id}/stock-adjust': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Adjust Stock */
    post: operations['adjust_stock_api_v1_admin_products__product_id__stock_adjust_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/admin/settings': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Settings */
    get: operations['read_settings_api_v1_admin_settings_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Update Settings */
    patch: operations['update_settings_api_v1_admin_settings_patch'];
    trace?: never;
  };
  '/api/v1/admin/uploads/images': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Upload Image */
    post: operations['upload_image_api_v1_admin_uploads_images_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/dev-login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Dev Login */
    post: operations['dev_login_api_v1_auth_dev_login_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/google': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Sign In With Google */
    post: operations['sign_in_with_google_api_v1_auth_google_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Logout */
    post: operations['logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Refresh */
    post: operations['refresh_api_v1_auth_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Cart */
    get: operations['get_cart_api_v1_cart_get'];
    put?: never;
    post?: never;
    /** Clear Cart */
    delete: operations['clear_cart_api_v1_cart_delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/cart/items/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Set Item Quantity
     * @description Sets an absolute quantity (0 removes). Safe to retry: the same call gives the same cart.
     */
    put: operations['set_item_quantity_api_v1_cart_items__product_id__put'];
    post?: never;
    /** Remove Item */
    delete: operations['remove_item_api_v1_cart_items__product_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Categories */
    get: operations['list_categories_api_v1_categories_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/categories/{slug}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Category */
    get: operations['get_category_api_v1_categories__slug__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/checkout/quote': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Checkout Quote
     * @description Prices come from the server only. Blocking problems are listed in `issues` rather than
     *     raised, so the checkout screen can show all of them at once.
     */
    post: operations['checkout_quote_api_v1_checkout_quote_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/favourites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Favourites */
    get: operations['list_favourites_api_v1_favourites_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/favourites/ids': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Favourite Ids
     * @description Lightweight: lets the app draw filled hearts without fetching full products.
     */
    get: operations['favourite_ids_api_v1_favourites_ids_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/favourites/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Add Favourite */
    put: operations['add_favourite_api_v1_favourites__product_id__put'];
    post?: never;
    /** Remove Favourite */
    delete: operations['remove_favourite_api_v1_favourites__product_id__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness: the process is up.
     */
    get: operations['health_api_v1_health_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health/db': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health Db
     * @description Readiness: the database answers.
     */
    get: operations['health_db_api_v1_health_db_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/home': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Home
     * @description Everything the home screen needs in one round trip.
     */
    get: operations['get_home_api_v1_home_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations['get_me_api_v1_me_get'];
    put?: never;
    post?: never;
    /** Delete Me */
    delete: operations['delete_me_api_v1_me_delete'];
    options?: never;
    head?: never;
    /** Update Me */
    patch: operations['update_me_api_v1_me_patch'];
    trace?: never;
  };
  '/api/v1/me/devices': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register Device */
    post: operations['register_device_api_v1_me_devices_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/me/devices/{token}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Remove Device */
    delete: operations['remove_device_api_v1_me_devices__token__delete'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Orders */
    get: operations['list_orders_api_v1_orders_get'];
    put?: never;
    /**
     * Place Order
     * @description Prices, stock and delivery rules are checked again here, inside one transaction.
     *     Resending the same `idempotency_key` returns the original order with 200.
     */
    post: operations['place_order_api_v1_orders_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/{order_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Order */
    get: operations['get_order_api_v1_orders__order_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/orders/{order_id}/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Cancel Order
     * @description Allowed only before the shop accepts the order; the stock goes back on the shelf.
     */
    post: operations['cancel_order_api_v1_orders__order_id__cancel_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Products */
    get: operations['list_products_api_v1_products_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/suggest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Suggest Products */
    get: operations['suggest_products_api_v1_products_suggest_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/products/{product_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Product */
    get: operations['get_product_api_v1_products__product_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/shop': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Shop */
    get: operations['get_shop_api_v1_shop_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AddressCreate */
    AddressCreate: {
      /** City */
      city: string;
      /**
       * Is Default
       * @default false
       */
      is_default?: boolean;
      /**
       * Label
       * @default Home
       */
      label?: string;
      /** Landmark */
      landmark?: string | null;
      /** Line1 */
      line1: string;
      /** Line2 */
      line2?: string | null;
      /** Phone */
      phone: string;
      /** Pincode */
      pincode: string;
      /** Recipient Name */
      recipient_name: string;
      /** State */
      state: string;
    };
    /** AddressOut */
    AddressOut: {
      /** City */
      city: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Is Default */
      is_default: boolean;
      /** Is Serviceable */
      is_serviceable: boolean;
      /** Label */
      label: string;
      /** Landmark */
      landmark: string | null;
      /** Line1 */
      line1: string;
      /** Line2 */
      line2: string | null;
      /** Phone */
      phone: string;
      /** Pincode */
      pincode: string;
      /** Recipient Name */
      recipient_name: string;
      /** State */
      state: string;
    };
    /**
     * AddressUpdate
     * @description Only the fields sent are changed. Use POST /addresses/{id}/default to change the default.
     */
    AddressUpdate: {
      /** City */
      city?: string | null;
      /** Label */
      label?: string | null;
      /** Landmark */
      landmark?: string | null;
      /** Line1 */
      line1?: string | null;
      /** Line2 */
      line2?: string | null;
      /** Phone */
      phone?: string | null;
      /** Pincode */
      pincode?: string | null;
      /** Recipient Name */
      recipient_name?: string | null;
      /** State */
      state?: string | null;
    };
    /** AdminBannerOut */
    AdminBannerOut: {
      /** Ends At */
      ends_at: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Key */
      image_key: string | null;
      /** Image Url */
      image_url: string | null;
      /** Is Active */
      is_active: boolean;
      /** Is Live */
      is_live: boolean;
      /** Sort Order */
      sort_order: number;
      /** Starts At */
      starts_at: string | null;
      /** Subtitle */
      subtitle: string | null;
      /** Target Id */
      target_id: string | null;
      /** Target Label */
      target_label: string | null;
      /**
       * Target Type
       * @enum {string}
       */
      target_type: 'NONE' | 'CATEGORY' | 'PRODUCT';
      /** Title */
      title: string;
    };
    /** AdminCategoryOut */
    AdminCategoryOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Key */
      image_key: string | null;
      /** Image Url */
      image_url: string | null;
      /** Is Active */
      is_active: boolean;
      /** Name */
      name: string;
      /** Product Count */
      product_count: number;
      /** Slug */
      slug: string;
      /** Sort Order */
      sort_order: number;
    };
    /** AdminOrderDetailOut */
    AdminOrderDetailOut: {
      /** Can Cancel */
      can_cancel: boolean;
      /** Cancel Reason */
      cancel_reason: string | null;
      customer: components['schemas']['CustomerOut'];
      /** Customer Note */
      customer_note: string | null;
      delivery_address: components['schemas']['DeliveryAddressOut'];
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Discount Paise */
      discount_paise: number;
      /** First Item Images */
      first_item_images: string[];
      /** History */
      history: components['schemas']['HistoryEntry'][];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Item Count */
      item_count: number;
      /** Items */
      items: components['schemas']['OrderItemOut'][];
      /** Next Statuses */
      next_statuses: components['schemas']['OrderStatus'][];
      /** Order Number */
      order_number: number;
      payment_method: components['schemas']['PaymentMethod'];
      payment_status: components['schemas']['PaymentStatus'];
      /**
       * Placed At
       * Format: date-time
       */
      placed_at: string;
      status: components['schemas']['OrderStatus'];
      /** Subtotal Paise */
      subtotal_paise: number;
      /** Timeline */
      timeline: components['schemas']['TimelineStep'][];
      /** Total Paise */
      total_paise: number;
    };
    /** AdminOrderRow */
    AdminOrderRow: {
      /** Customer Name */
      customer_name: string;
      /** Customer Phone */
      customer_phone: string;
      /** Delivery Area */
      delivery_area: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Item Count */
      item_count: number;
      /** Order Number */
      order_number: number;
      payment_method: components['schemas']['PaymentMethod'];
      payment_status: components['schemas']['PaymentStatus'];
      /**
       * Placed At
       * Format: date-time
       */
      placed_at: string;
      status: components['schemas']['OrderStatus'];
      /** Total Paise */
      total_paise: number;
    };
    /** AdminProductOut */
    AdminProductOut: {
      /** Archived At */
      archived_at: string | null;
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Category Name */
      category_name: string;
      /** Description */
      description: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Key */
      image_key: string | null;
      /** Image Url */
      image_url: string | null;
      /** Is Active */
      is_active: boolean;
      /** Is Featured */
      is_featured: boolean;
      /** Is Low Stock */
      is_low_stock: boolean;
      /** Low Stock Threshold */
      low_stock_threshold: number | null;
      /** Max Per Order */
      max_per_order: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /** Search Keywords */
      search_keywords: string | null;
      /** Slug */
      slug: string;
      /** Stock Quantity */
      stock_quantity: number;
      /** Unit Label */
      unit_label: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
    };
    /** AdminSettingsOut */
    AdminSettingsOut: {
      /** Closed Message */
      closed_message: string;
      /** Cod Enabled */
      cod_enabled: boolean;
      /** Default Low Stock Threshold */
      default_low_stock_threshold: number;
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Empty Pincodes Accept All */
      empty_pincodes_accept_all: boolean;
      /** Free Delivery Above Paise */
      free_delivery_above_paise: number;
      /** Is Accepting Orders */
      is_accepting_orders: boolean;
      /** Min Order Paise */
      min_order_paise: number;
      /** Online Payment Enabled */
      online_payment_enabled: boolean;
      /** Payment Timeout Minutes */
      payment_timeout_minutes: number;
      /** Serviceable Pincodes */
      serviceable_pincodes: string[];
      /** Shop Address */
      shop_address: string | null;
      /** Shop Name */
      shop_name: string;
      /** Shop Phone */
      shop_phone: string | null;
      /** Updated At */
      updated_at: string | null;
    };
    /**
     * AdminSettingsUpdate
     * @description Only the fields sent are changed.
     */
    AdminSettingsUpdate: {
      /** Closed Message */
      closed_message?: string | null;
      /** Cod Enabled */
      cod_enabled?: boolean | null;
      /** Default Low Stock Threshold */
      default_low_stock_threshold?: number | null;
      /** Delivery Fee Paise */
      delivery_fee_paise?: number | null;
      /** Free Delivery Above Paise */
      free_delivery_above_paise?: number | null;
      /** Is Accepting Orders */
      is_accepting_orders?: boolean | null;
      /** Min Order Paise */
      min_order_paise?: number | null;
      /** Online Payment Enabled */
      online_payment_enabled?: boolean | null;
      /** Payment Timeout Minutes */
      payment_timeout_minutes?: number | null;
      /** Serviceable Pincodes */
      serviceable_pincodes?: string[] | null;
      /** Shop Address */
      shop_address?: string | null;
      /** Shop Name */
      shop_name?: string | null;
      /** Shop Phone */
      shop_phone?: string | null;
    };
    /** AuthResponse */
    AuthResponse: {
      /** Access Token */
      access_token: string;
      /** Expires In */
      expires_in: number;
      /** Is New User */
      is_new_user: boolean;
      /** Refresh Token */
      refresh_token?: string | null;
      /**
       * Token Type
       * @default bearer
       * @constant
       */
      token_type?: 'bearer';
      user: components['schemas']['UserOut'];
    };
    /** BannerCreate */
    BannerCreate: {
      /** Ends At */
      ends_at?: string | null;
      /** Image Key */
      image_key?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /** Starts At */
      starts_at?: string | null;
      /** Subtitle */
      subtitle?: string | null;
      /** Target Id */
      target_id?: string | null;
      /**
       * Target Type
       * @default NONE
       * @enum {string}
       */
      target_type?: 'NONE' | 'CATEGORY' | 'PRODUCT';
      /** Title */
      title: string;
    };
    /** BannerOut */
    BannerOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Subtitle */
      subtitle: string | null;
      /** Target Id */
      target_id: string | null;
      /** Target Slug */
      target_slug: string | null;
      /**
       * Target Type
       * @enum {string}
       */
      target_type: 'NONE' | 'CATEGORY' | 'PRODUCT';
      /** Title */
      title: string;
    };
    /** BannerUpdate */
    BannerUpdate: {
      /** Ends At */
      ends_at?: string | null;
      /** Image Key */
      image_key?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /**
       * Remove Image
       * @default false
       */
      remove_image?: boolean;
      /** Starts At */
      starts_at?: string | null;
      /** Subtitle */
      subtitle?: string | null;
      /** Target Id */
      target_id?: string | null;
      /** Target Type */
      target_type?: ('NONE' | 'CATEGORY' | 'PRODUCT') | null;
      /** Title */
      title?: string | null;
    };
    /** Body_upload_image_api_v1_admin_uploads_images_post */
    Body_upload_image_api_v1_admin_uploads_images_post: {
      /** File */
      file: string;
    };
    /** CancelOrderRequest */
    CancelOrderRequest: {
      /** Reason */
      reason?: string | null;
    };
    /** CartLineOut */
    CartLineOut: {
      /** Available Quantity */
      available_quantity: number;
      /** Issue */
      issue: ('UNAVAILABLE' | 'OUT_OF_STOCK' | 'QUANTITY_REDUCED') | null;
      /** Line Total Paise */
      line_total_paise: number;
      product: components['schemas']['ProductCardOut'];
      /** Quantity */
      quantity: number;
    };
    /** CartOut */
    CartOut: {
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Free Delivery Remaining Paise */
      free_delivery_remaining_paise: number;
      /** Has Issues */
      has_issues: boolean;
      /** Item Count */
      item_count: number;
      /** Lines */
      lines: components['schemas']['CartLineOut'][];
      /** Min Order Remaining Paise */
      min_order_remaining_paise: number;
      rules: components['schemas']['DeliveryRules'];
      /** Subtotal Paise */
      subtotal_paise: number;
      /** Total Paise */
      total_paise: number;
    };
    /** CategoryCreate */
    CategoryCreate: {
      /** Image Key */
      image_key?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /** Name */
      name: string;
    };
    /** CategoryOut */
    CategoryOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** CategoryRef */
    CategoryRef: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Slug */
      slug: string;
    };
    /** CategoryUpdate */
    CategoryUpdate: {
      /** Image Key */
      image_key?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Name */
      name?: string | null;
      /**
       * Remove Image
       * @default false
       */
      remove_image?: boolean;
    };
    /** CheckoutIssue */
    CheckoutIssue: {
      /**
       * Code
       * @enum {string}
       */
      code:
        | 'SHOP_CLOSED'
        | 'NOT_SERVICEABLE'
        | 'BELOW_MIN_ORDER'
        | 'ITEMS_CHANGED'
        | 'EMPTY_ORDER'
        | 'NO_PAYMENT_METHOD';
      /** Message */
      message: string;
    };
    /** CheckoutItem */
    CheckoutItem: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Quantity */
      quantity: number;
    };
    /**
     * CheckoutQuoteOut
     * @description Exactly what placing the order would charge right now. Computing it changes nothing.
     */
    CheckoutQuoteOut: {
      address: components['schemas']['AddressOut'];
      /** Can Place Order */
      can_place_order: boolean;
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Issues */
      issues: components['schemas']['CheckoutIssue'][];
      /** Item Count */
      item_count: number;
      /** Lines */
      lines: components['schemas']['CartLineOut'][];
      /** Payment Methods */
      payment_methods: ('COD' | 'ONLINE')[];
      /** Subtotal Paise */
      subtotal_paise: number;
      /** Total Paise */
      total_paise: number;
    };
    /** CheckoutQuoteRequest */
    CheckoutQuoteRequest: {
      /**
       * Address Id
       * Format: uuid
       */
      address_id: string;
      /** Items */
      items: components['schemas']['CheckoutItem'][];
    };
    /** CustomerOut */
    CustomerOut: {
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Phone */
      phone: string | null;
    };
    /** DashboardOut */
    DashboardOut: {
      /** Low Stock */
      low_stock: components['schemas']['LowStockItem'][];
      /** Recent Orders */
      recent_orders: components['schemas']['AdminOrderRow'][];
      /** Status Counts */
      status_counts: {
        [key: string]: number;
      };
      /** Today Orders */
      today_orders: number;
      /** Today Revenue Paise */
      today_revenue_paise: number;
    };
    /** DeliveryAddressOut */
    DeliveryAddressOut: {
      /** City */
      city: string;
      /** Landmark */
      landmark: string | null;
      /** Line1 */
      line1: string;
      /** Line2 */
      line2: string | null;
      /** Name */
      name: string;
      /** Phone */
      phone: string;
      /** Pincode */
      pincode: string;
      /** State */
      state: string;
    };
    /**
     * DeliveryRules
     * @description Sent so the app can estimate totals instantly while a change is in flight.
     */
    DeliveryRules: {
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Free Delivery Above Paise */
      free_delivery_above_paise: number;
      /** Min Order Paise */
      min_order_paise: number;
    };
    /** DevSignInRequest */
    DevSignInRequest: {
      /** @default mobile */
      client?: components['schemas']['SessionClient'];
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Name */
      name?: string | null;
    };
    /** DeviceRegistration */
    DeviceRegistration: {
      /**
       * Platform
       * @default android
       * @constant
       */
      platform?: 'android';
      /** Token */
      token: string;
    };
    /** GoogleSignInRequest */
    GoogleSignInRequest: {
      /** @default mobile */
      client?: components['schemas']['SessionClient'];
      /** Id Token */
      id_token: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status?: 'ok';
    };
    /** HistoryEntry */
    HistoryEntry: {
      /**
       * Actor
       * @enum {string}
       */
      actor: 'CUSTOMER' | 'ADMIN' | 'SYSTEM';
      /** Actor Name */
      actor_name: string | null;
      /**
       * At
       * Format: date-time
       */
      at: string;
      from_status: components['schemas']['OrderStatus'] | null;
      /** Note */
      note: string | null;
      to_status: components['schemas']['OrderStatus'];
    };
    /** HomeOut */
    HomeOut: {
      /** Banners */
      banners: components['schemas']['BannerOut'][];
      /** Categories */
      categories: components['schemas']['CategoryOut'][];
      /** Featured */
      featured: components['schemas']['ProductCardOut'][];
    };
    /** LogoutRequest */
    LogoutRequest: {
      /** Device Token */
      device_token?: string | null;
    };
    /** LowStockItem */
    LowStockItem: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Stock Quantity */
      stock_quantity: number;
      /** Threshold */
      threshold: number;
      /** Unit Label */
      unit_label: string;
    };
    /** OrderDetailOut */
    OrderDetailOut: {
      /** Can Cancel */
      can_cancel: boolean;
      /** Cancel Reason */
      cancel_reason: string | null;
      /** Customer Note */
      customer_note: string | null;
      delivery_address: components['schemas']['DeliveryAddressOut'];
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Discount Paise */
      discount_paise: number;
      /** First Item Images */
      first_item_images: string[];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Item Count */
      item_count: number;
      /** Items */
      items: components['schemas']['OrderItemOut'][];
      /** Order Number */
      order_number: number;
      payment_method: components['schemas']['PaymentMethod'];
      payment_status: components['schemas']['PaymentStatus'];
      /**
       * Placed At
       * Format: date-time
       */
      placed_at: string;
      status: components['schemas']['OrderStatus'];
      /** Subtotal Paise */
      subtotal_paise: number;
      /** Timeline */
      timeline: components['schemas']['TimelineStep'][];
      /** Total Paise */
      total_paise: number;
    };
    /** OrderItemOut */
    OrderItemOut: {
      /** Image Url */
      image_url: string | null;
      /** Line Total Paise */
      line_total_paise: number;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Quantity */
      quantity: number;
      /** Unit Label */
      unit_label: string;
      /** Unit Price Paise */
      unit_price_paise: number;
    };
    /**
     * OrderStatus
     * @enum {string}
     */
    OrderStatus:
      | 'AWAITING_PAYMENT'
      | 'PENDING'
      | 'CONFIRMED'
      | 'PREPARING'
      | 'OUT_FOR_DELIVERY'
      | 'DELIVERED'
      | 'CANCELLED';
    /** OrderSummaryOut */
    OrderSummaryOut: {
      /** First Item Images */
      first_item_images: string[];
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Item Count */
      item_count: number;
      /** Order Number */
      order_number: number;
      payment_method: components['schemas']['PaymentMethod'];
      payment_status: components['schemas']['PaymentStatus'];
      /**
       * Placed At
       * Format: date-time
       */
      placed_at: string;
      status: components['schemas']['OrderStatus'];
      /** Total Paise */
      total_paise: number;
    };
    /**
     * OrdersSummaryOut
     * @description Polled by the admin every 15 s to announce new orders.
     */
    OrdersSummaryOut: {
      /** Latest Order At */
      latest_order_at: string | null;
      /** Pending Count */
      pending_count: number;
    };
    /** Page[AdminOrderRow] */
    Page_AdminOrderRow_: {
      /** Items */
      items: components['schemas']['AdminOrderRow'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[AdminProductOut] */
    Page_AdminProductOut_: {
      /** Items */
      items: components['schemas']['AdminProductOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[OrderSummaryOut] */
    Page_OrderSummaryOut_: {
      /** Items */
      items: components['schemas']['OrderSummaryOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** Page[ProductCardOut] */
    Page_ProductCardOut_: {
      /** Items */
      items: components['schemas']['ProductCardOut'][];
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /**
     * PaymentMethod
     * @enum {string}
     */
    PaymentMethod: 'ONLINE' | 'COD';
    /**
     * PaymentStatus
     * @enum {string}
     */
    PaymentStatus: 'PENDING' | 'PAID' | 'FAILED' | 'REFUNDED' | 'REFUND_FAILED';
    /** PlaceOrderOut */
    PlaceOrderOut: {
      order: components['schemas']['OrderDetailOut'];
      /** Payment */
      payment?: null;
    };
    /** PlaceOrderRequest */
    PlaceOrderRequest: {
      /**
       * Address Id
       * Format: uuid
       */
      address_id: string;
      /** Customer Note */
      customer_note?: string | null;
      /** Expected Total Paise */
      expected_total_paise: number;
      /**
       * Idempotency Key
       * Format: uuid
       */
      idempotency_key: string;
      /** Items */
      items: components['schemas']['CheckoutItem'][];
      payment_method: components['schemas']['PaymentMethod'];
    };
    /** ProductCardOut */
    ProductCardOut: {
      /** Discount Percent */
      discount_percent: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Is Available */
      is_available: boolean;
      /** Max Per Order */
      max_per_order: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /**
       * Stock Hint
       * @enum {string}
       */
      stock_hint: 'IN_STOCK' | 'LOW' | 'OUT';
      /** Unit Label */
      unit_label: string;
    };
    /** ProductCreate */
    ProductCreate: {
      /**
       * Category Id
       * Format: uuid
       */
      category_id: string;
      /** Description */
      description?: string | null;
      /** Image Key */
      image_key?: string | null;
      /**
       * Is Active
       * @default true
       */
      is_active?: boolean;
      /**
       * Is Featured
       * @default false
       */
      is_featured?: boolean;
      /** Low Stock Threshold */
      low_stock_threshold?: number | null;
      /** Max Per Order */
      max_per_order?: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /** Search Keywords */
      search_keywords?: string | null;
      /**
       * Stock Quantity
       * @default 0
       */
      stock_quantity?: number;
      /** Unit Label */
      unit_label: string;
    };
    /** ProductDetailOut */
    ProductDetailOut: {
      category: components['schemas']['CategoryRef'];
      /** Description */
      description: string | null;
      /** Discount Percent */
      discount_percent: number;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Is Available */
      is_available: boolean;
      /** Max Per Order */
      max_per_order: number | null;
      /** Mrp Paise */
      mrp_paise: number;
      /** Name */
      name: string;
      /** Price Paise */
      price_paise: number;
      /** Related */
      related: components['schemas']['ProductCardOut'][];
      /**
       * Stock Hint
       * @enum {string}
       */
      stock_hint: 'IN_STOCK' | 'LOW' | 'OUT';
      /** Unit Label */
      unit_label: string;
    };
    /**
     * ProductUpdate
     * @description Stock is not editable here: it goes through the stock endpoints so every change is logged.
     */
    ProductUpdate: {
      /** Category Id */
      category_id?: string | null;
      /** Description */
      description?: string | null;
      /** Image Key */
      image_key?: string | null;
      /** Is Active */
      is_active?: boolean | null;
      /** Is Featured */
      is_featured?: boolean | null;
      /** Low Stock Threshold */
      low_stock_threshold?: number | null;
      /** Max Per Order */
      max_per_order?: number | null;
      /** Mrp Paise */
      mrp_paise?: number | null;
      /** Name */
      name?: string | null;
      /** Price Paise */
      price_paise?: number | null;
      /**
       * Remove Image
       * @default false
       */
      remove_image?: boolean;
      /** Search Keywords */
      search_keywords?: string | null;
      /** Unit Label */
      unit_label?: string | null;
    };
    /** RefreshRequest */
    RefreshRequest: {
      /** Refresh Token */
      refresh_token?: string | null;
    };
    /** ReorderRequest */
    ReorderRequest: {
      /** Ids */
      ids: string[];
    };
    /**
     * SessionClient
     * @enum {string}
     */
    SessionClient: 'mobile' | 'admin';
    /** SetQuantityRequest */
    SetQuantityRequest: {
      /**
       * Quantity
       * @description 0 removes the item
       */
      quantity: number;
    };
    /** ShopOut */
    ShopOut: {
      /** Closed Message */
      closed_message: string;
      /** Cod Enabled */
      cod_enabled: boolean;
      /** Delivery Fee Paise */
      delivery_fee_paise: number;
      /** Free Delivery Above Paise */
      free_delivery_above_paise: number;
      /** Is Accepting Orders */
      is_accepting_orders: boolean;
      /** Min Order Paise */
      min_order_paise: number;
      /** Name */
      name: string;
      /** Online Payment Enabled */
      online_payment_enabled: boolean;
      /** Phone */
      phone: string | null;
    };
    /** StatusChangeRequest */
    StatusChangeRequest: {
      /** Note */
      note?: string | null;
      to_status: components['schemas']['OrderStatus'];
    };
    /** StockAdjustRequest */
    StockAdjustRequest: {
      /** Delta */
      delta: number;
      /** Note */
      note?: string | null;
    };
    /** StockOut */
    StockOut: {
      /**
       * Product Id
       * Format: uuid
       */
      product_id: string;
      /** Stock Quantity */
      stock_quantity: number;
    };
    /** StockSetRequest */
    StockSetRequest: {
      /** Expected Stock */
      expected_stock: number;
      /** Stock */
      stock: number;
    };
    /** SuggestionOut */
    SuggestionOut: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Image Url */
      image_url: string | null;
      /** Name */
      name: string;
      /** Unit Label */
      unit_label: string;
    };
    /** TimelineStep */
    TimelineStep: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      status: components['schemas']['OrderStatus'];
    };
    /** UpdateMeRequest */
    UpdateMeRequest: {
      /** Name */
      name?: string | null;
      /** Phone */
      phone?: string | null;
    };
    /** UploadOut */
    UploadOut: {
      /** Key */
      key: string;
      /** Url */
      url: string;
    };
    /** UserOut */
    UserOut: {
      /** Avatar Url */
      avatar_url: string | null;
      /** Email */
      email: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Needs Onboarding */
      needs_onboarding: boolean;
      /** Phone */
      phone: string | null;
      role: components['schemas']['UserRole'];
    };
    /**
     * UserRole
     * @enum {string}
     */
    UserRole: 'CUSTOMER' | 'ADMIN';
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_addresses_api_v1_addresses_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressOut'][];
        };
      };
    };
  };
  create_address_api_v1_addresses_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddressCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_address_api_v1_addresses__address_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_address_api_v1_addresses__address_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AddressUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_default_address_api_v1_addresses__address_id__default_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        address_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AddressOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_banners_api_v1_admin_banners_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminBannerOut'][];
        };
      };
    };
  };
  create_banner_api_v1_admin_banners_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BannerCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminBannerOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reorder_banners_api_v1_admin_banners_reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_banner_api_v1_admin_banners__banner_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        banner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_banner_api_v1_admin_banners__banner_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        banner_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BannerUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminBannerOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_categories_api_v1_admin_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategoryOut'][];
        };
      };
    };
  };
  create_category_api_v1_admin_categories_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  reorder_categories_api_v1_admin_categories_reorder_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  delete_category_api_v1_admin_categories__category_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_category_api_v1_admin_categories__category_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        category_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CategoryUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminCategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  dashboard_api_v1_admin_dashboard_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DashboardOut'];
        };
      };
    };
  };
  list_orders_api_v1_admin_orders_get: {
    parameters: {
      query?: {
        status?: components['schemas']['OrderStatus'] | null;
        payment_status?: components['schemas']['PaymentStatus'] | null;
        q?: string | null;
        from?: string | null;
        to?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AdminOrderRow_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  orders_summary_api_v1_admin_orders_summary_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrdersSummaryOut'];
        };
      };
    };
  };
  get_order_api_v1_admin_orders__order_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminOrderDetailOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  change_status_api_v1_admin_orders__order_id__status_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StatusChangeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminOrderDetailOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_products_api_v1_admin_products_get: {
    parameters: {
      query?: {
        q?: string | null;
        category_id?: string | null;
        status?: 'active' | 'inactive' | 'archived' | 'all';
        low_stock?: boolean;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_AdminProductOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  create_product_api_v1_admin_products_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_product_api_v1_admin_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  archive_product_api_v1_admin_products__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  update_product_api_v1_admin_products__product_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProductUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  restore_product_api_v1_admin_products__product_id__restore_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminProductOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  set_stock_api_v1_admin_products__product_id__stock_patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StockSetRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StockOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  adjust_stock_api_v1_admin_products__product_id__stock_adjust_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['StockAdjustRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StockOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  read_settings_api_v1_admin_settings_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSettingsOut'];
        };
      };
    };
  };
  update_settings_api_v1_admin_settings_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AdminSettingsUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AdminSettingsOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  upload_image_api_v1_admin_uploads_images_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_image_api_v1_admin_uploads_images_post'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UploadOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  dev_login_api_v1_auth_dev_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DevSignInRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  sign_in_with_google_api_v1_auth_google_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['GoogleSignInRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['LogoutRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  refresh_api_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['RefreshRequest'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AuthResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_cart_api_v1_cart_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
    };
  };
  clear_cart_api_v1_cart_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
    };
  };
  set_item_quantity_api_v1_cart_items__product_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SetQuantityRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_item_api_v1_cart_items__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CartOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_categories_api_v1_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOut'][];
        };
      };
    };
  };
  get_category_api_v1_categories__slug__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CategoryOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  checkout_quote_api_v1_checkout_quote_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CheckoutQuoteRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CheckoutQuoteOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_favourites_api_v1_favourites_get: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ProductCardOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  favourite_ids_api_v1_favourites_ids_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': string[];
        };
      };
    };
  };
  add_favourite_api_v1_favourites__product_id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_favourite_api_v1_favourites__product_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  health_api_v1_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  health_db_api_v1_health_db_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthResponse'];
        };
      };
    };
  };
  get_home_api_v1_home_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HomeOut'];
        };
      };
    };
  };
  get_me_api_v1_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
    };
  };
  delete_me_api_v1_me_delete: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  update_me_api_v1_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateMeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  register_device_api_v1_me_devices_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeviceRegistration'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  remove_device_api_v1_me_devices__token__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_orders_api_v1_orders_get: {
    parameters: {
      query?: {
        scope?: 'active' | 'past';
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_OrderSummaryOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  place_order_api_v1_orders_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PlaceOrderRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PlaceOrderOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_order_api_v1_orders__order_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderDetailOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  cancel_order_api_v1_orders__order_id__cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        order_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CancelOrderRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['OrderDetailOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  list_products_api_v1_products_get: {
    parameters: {
      query?: {
        /** @description Search text; ranks by relevance */
        q?: string | null;
        category_id?: string | null;
        in_stock_only?: boolean;
        sort?: 'default' | 'price_asc' | 'price_desc';
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['Page_ProductCardOut_'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  suggest_products_api_v1_products_suggest_get: {
    parameters: {
      query: {
        q: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SuggestionOut'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_product_api_v1_products__product_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        product_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ProductDetailOut'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_shop_api_v1_shop_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShopOut'];
        };
      };
    };
  };
}
