"""catalog, inventory log and shop settings

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-29 20:44:08.110462
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_table('shop_settings',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('shop_name', sa.Text(), nullable=False),
    sa.Column('shop_phone', sa.Text(), nullable=True),
    sa.Column('shop_address', sa.Text(), nullable=True),
    sa.Column('is_accepting_orders', sa.Boolean(), nullable=False),
    sa.Column('closed_message', sa.Text(), nullable=False),
    sa.Column('delivery_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('free_delivery_above_paise', sa.BigInteger(), nullable=False),
    sa.Column('min_order_paise', sa.BigInteger(), nullable=False),
    sa.Column('serviceable_pincodes', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('cod_enabled', sa.Boolean(), nullable=False),
    sa.Column('online_payment_enabled', sa.Boolean(), nullable=False),
    sa.Column('payment_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('default_low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name=op.f('ck_shop_settings_single_row')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shop_settings'))
    )
    op.create_table('products',
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit_label', sa.Text(), nullable=False),
    sa.Column('price_paise', sa.BigInteger(), nullable=False),
    sa.Column('mrp_paise', sa.BigInteger(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=True),
    sa.Column('max_per_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('search_keywords', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('low_stock_threshold IS NULL OR low_stock_threshold >= 0', name=op.f('ck_products_low_stock_threshold_not_negative')),
    sa.CheckConstraint('max_per_order IS NULL OR max_per_order > 0', name=op.f('ck_products_max_per_order_positive')),
    sa.CheckConstraint('mrp_paise >= price_paise', name=op.f('ck_products_mrp_not_below_price')),
    sa.CheckConstraint('price_paise > 0', name=op.f('ck_products_price_positive')),
    sa.CheckConstraint('stock_quantity >= 0', name=op.f('ck_products_stock_not_negative')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    sa.UniqueConstraint('slug', name=op.f('uq_products_slug'))
    )
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    op.create_index('ix_products_category_listing', 'products', ['category_id', 'is_active', 'sort_order'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('resulting_stock', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Enum('INITIAL', 'ORDER_PLACED', 'ORDER_CANCELLED', 'MANUAL_ADJUST', 'STOCK_SET', name='inventory_reason'), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_inventory_movements_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inventory_movements_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movements'))
    )
    op.create_index('ix_inventory_movements_product_time', 'inventory_movements', ['product_id', 'created_at'], unique=False)
    # ### end Alembic commands ###

    # The single settings row, with placeholder delivery rules until the shopkeeper sets them.
    op.execute(
        """
        INSERT INTO shop_settings (
            id, shop_name, is_accepting_orders, closed_message, delivery_fee_paise,
            free_delivery_above_paise, min_order_paise, serviceable_pincodes, cod_enabled,
            online_payment_enabled, payment_timeout_minutes, default_low_stock_threshold
        ) VALUES (
            1, 'Bada Bazar', true, 'We''re closed right now. Back tomorrow at 8 AM.', 2000,
            29900, 9900, '{}', true, true, 15, 5
        )
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inventory_movements_product_time', table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index('ix_products_category_listing', table_name='products')
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.drop_table('products')
    op.drop_table('shop_settings')
    op.drop_table('categories')
    # ### end Alembic commands ###
    sa.Enum(name='inventory_reason').drop(op.get_bind(), checkfirst=True)
