"""banners and product search index

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-29 21:21:53.095687
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banners',
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('image_key', sa.Text(), nullable=True),
    sa.Column('target_type', sa.Enum('NONE', 'CATEGORY', 'PRODUCT', name='banner_target'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(target_type = 'NONE') = (target_id IS NULL)", name=op.f('ck_banners_target_id_matches_type')),
    sa.CheckConstraint('ends_at IS NULL OR starts_at IS NULL OR ends_at > starts_at', name=op.f('ck_banners_ends_after_start')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_banners'))
    )
    # ### end Alembic commands ###

    # Trigram index for product search. The expression must stay identical to
    # app.repositories.catalog.SEARCH_TEXT. Excluded from autogenerate in alembic/env.py.
    op.execute(
        "CREATE INDEX ix_products_search_trgm ON products USING gin "
        "(lower(name || ' ' || coalesce(search_keywords, '')) gin_trgm_ops)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banners')
    # ### end Alembic commands ###
    op.execute("DROP INDEX IF EXISTS ix_products_search_trgm")
    sa.Enum(name='banner_target').drop(op.get_bind(), checkfirst=True)
