"""orders and payments

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-29 22:57:22.117463
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column(
            "order_number", sa.BigInteger(), sa.Identity(always=True, start=10001), nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AWAITING_PAYMENT",
                "PENDING",
                "CONFIRMED",
                "PREPARING",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "CANCELLED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column(
            "payment_method", sa.Enum("ONLINE", "COD", name="payment_method"), nullable=False
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "PENDING", "PAID", "FAILED", "REFUNDED", "REFUND_FAILED", name="payment_status"
            ),
            nullable=False,
        ),
        sa.Column("subtotal_paise", sa.BigInteger(), nullable=False),
        sa.Column("delivery_fee_paise", sa.BigInteger(), nullable=False),
        sa.Column("discount_paise", sa.BigInteger(), nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("delivery_name", sa.Text(), nullable=False),
        sa.Column("delivery_phone", sa.Text(), nullable=False),
        sa.Column("delivery_line1", sa.Text(), nullable=False),
        sa.Column("delivery_line2", sa.Text(), nullable=True),
        sa.Column("delivery_landmark", sa.Text(), nullable=True),
        sa.Column("delivery_city", sa.Text(), nullable=False),
        sa.Column("delivery_state", sa.Text(), nullable=False),
        sa.Column("delivery_pincode", sa.Text(), nullable=False),
        sa.Column("customer_note", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.Uuid(), nullable=False),
        sa.Column("payment_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("cancelled_by", sa.Uuid(), nullable=True),
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_fee_paise >= 0 AND discount_paise >= 0",
            name=op.f("ck_orders_fees_not_negative"),
        ),
        sa.CheckConstraint("subtotal_paise > 0", name=op.f("ck_orders_subtotal_positive")),
        sa.CheckConstraint(
            "total_paise = subtotal_paise + delivery_fee_paise - discount_paise",
            name=op.f("ck_orders_total_adds_up"),
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by"],
            ["users.id"],
            name=op.f("fk_orders_cancelled_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
        sa.UniqueConstraint("user_id", "idempotency_key", name="uq_orders_user_idempotency_key"),
    )
    op.create_index(
        "ix_orders_awaiting_payment_expiry",
        "orders",
        ["payment_expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'AWAITING_PAYMENT'"),
    )
    op.create_index(
        "ix_orders_status_placed",
        "orders",
        ["status", sa.literal_column("placed_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_orders_user_placed",
        "orders",
        ["user_id", sa.literal_column("placed_at DESC")],
        unique=False,
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.Text(), nullable=False),
        sa.Column("unit_label", sa.Text(), nullable=False),
        sa.Column("image_key", sa.Text(), nullable=True),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("mrp_paise", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("line_total_paise", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.CheckConstraint(
            "line_total_paise = unit_price_paise * quantity",
            name=op.f("ck_order_items_line_adds_up"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_items_product_id"), "order_items", ["product_id"], unique=False)
    op.create_table(
        "order_status_history",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "AWAITING_PAYMENT",
                "PENDING",
                "CONFIRMED",
                "PREPARING",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "CANCELLED",
                name="order_status",
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "AWAITING_PAYMENT",
                "PENDING",
                "CONFIRMED",
                "PREPARING",
                "OUT_FOR_DELIVERY",
                "DELIVERED",
                "CANCELLED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_order_status_history_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index(
        "ix_order_status_history_order_time",
        "order_status_history",
        ["order_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "payments",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("provider_order_id", sa.Text(), nullable=False),
        sa.Column("provider_payment_id", sa.Text(), nullable=True),
        sa.Column("amount_paise", sa.BigInteger(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "CAPTURED",
                "FAILED",
                "REFUNDED",
                "REFUND_FAILED",
                name="payment_attempt_status",
            ),
            nullable=False,
        ),
        sa.Column("method", sa.Text(), nullable=True),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("refund_id", sa.Text(), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("needs_review", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("provider_order_id", name=op.f("uq_payments_provider_order_id")),
        sa.UniqueConstraint("provider_payment_id", name=op.f("uq_payments_provider_payment_id")),
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_inventory_movements_order_id"), "inventory_movements", ["order_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_inventory_movements_order_id_orders"),
        "inventory_movements",
        "orders",
        ["order_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_inventory_movements_order_id_orders"), "inventory_movements", type_="foreignkey"
    )
    op.drop_index(op.f("ix_inventory_movements_order_id"), table_name="inventory_movements")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index("ix_order_status_history_order_time", table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index(op.f("ix_order_items_product_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_orders_user_placed", table_name="orders")
    op.drop_index("ix_orders_status_placed", table_name="orders")
    op.drop_index(
        "ix_orders_awaiting_payment_expiry",
        table_name="orders",
        postgresql_where=sa.text("status = 'AWAITING_PAYMENT'"),
    )
    op.drop_table("orders")
    # ### end Alembic commands ###
    for enum_name in ("payment_attempt_status", "payment_status", "payment_method", "order_status"):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
